version: '3'
services:
  redis:
    image: redis:6.2-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 20 1 --loglevel warning --port ${REDIS_PORT}
    networks:
      - my-network
    volumes:
      - redis_data_1:/data

  db:
    image: postgres:15.3
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    ports:
      - "${DB_PORT}:5432"
    networks:
      - my-network
    volumes:
      - db:/var/lib/postgresql/data

networks:
  my-network:

volumes:
  redis_data_1:
  db:
