version: '3'
services:
  bull_monitor:
    image: hocptit/bull_ui:0.0.2
    environment:
      REDIS_URI: "redis://redis:${REDIS_PORT}"
      USERNAME: "admin"
      PASSWORD: "Qaz12345#"
      QUEUES: "DATA_CRAWLER_CONTRACT_CRAWLER,DATA_CRAWLER_CONTRACT_SUBMITTER,MAIL_QUEUE,EVENT_QUEUE"
    ports:
      - "${BULL_MONITOR_PORT}:3011"
    depends_on:
      - redis
    networks:
      - my-network

  redis:
    image: redis:6.2-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 20 1 --loglevel warning --port ${REDIS_PORT}
    networks:
      - my-network
    volumes:
      - redis_data_1:/data

  db:
    image: postgres:15.3
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    ports:
      - "${DB_PORT}:5432"
    networks:
      - my-network
    volumes:
      - db:/var/lib/postgresql/data

networks:
  my-network:

volumes:
  redis_data_1:
  db:
