version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:${PORT}"
    volumes:
      - /app/node_modules
      - uploads_data:/uploads
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - my-network

  redis:
    image: redis:6.2-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 20 1 --loglevel warning --port ${REDIS_PORT}
    networks:
      - my-network
    volumes:
      - redis_data_1:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "${REDIS_PORT}", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db:
    image: postgres:15.3
    networks:
      - my-network
    ports:
      - "5432:5432"  # Add this line to expose PostgreSQL port
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      # Add these environment variables to allow external connections
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_LISTEN_ADDRESSES=*
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  my-network:
    driver: bridge

volumes:
  redis_data_1:
  db:
  uploads_data: